# Generated by Django 3.2.3 on 2021-06-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20210601_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username',
        ),
    ]
