# Generated by Django 3.2.3 on 2021-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20210602_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-06-05'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-06-05'),
        ),
    ]
